### ISSUE TITLE
Bug in preliminary MoveElse

### ISSUE THREAD

**Issue by ibbem** [VariantSync/DiffDetective#60]
During refactoring for #59 I found the following possible bug in `preliminary/pattern/semantic/MoveElse.java`. I did not test if this is actually a bug, but I'm pretty sure.

The following lines (38-42 on 93f836e387c325078b5ee77dca796b0e022f2e75)
```java
Collection<DiffNode> commonAddElse = annotationNode.getAllChildren();
commonAddElse.retainAll(annotationNode.getParent(AFTER).getAllChildren());

Collection<DiffNode> commonRemElse = removedElse.getAllChildren();
commonRemElse.retainAll(annotationNode.getParent(AFTER).getAllChildren());
```
modify the collection returned by `DiffNode.getAllChildren` by using `Collection.retainAll`. The problem is that `DiffNode.getAllChildren` returns an unmodifiable collection since 0a4b31826fecaf9d984392ce20b71d6f7302135b. Therefore this will result in an `UnsupportedOperationException` exception.

**Comment by pmbittner** [comment]
This code belongs the the bachelor's thesis of @sjvie . This might be a bug or might be not. In any case, I marked the whole package as deprecated. The original state of DiffDetective back then can be found on the separate, protected branch `thesis_sv` for reproducability. Since the edit classification in DiffDetective was renewed (both conceptually and implementation-wise), this package is now deprecated but I still kept it. We could decide to remove this package alltogether as it is not needed anymore. In any case, there is no need to invest time in fixing any bugs.
